export default function Clinics() {
  return [
    {
      resource: "Eve-Medical Clinic",
      address: {
        street: "8603 South Dixie Hwy.",
        apt: "102",
        city: "Miami",
        state: "FL",
        zipCode: "33143",
      },
      coordinate: {
        latitude: 25.6902481,
        longitude: -80.3060794,
      },
      phoneNumber: "305-707-6096",
      website: "evemedicalmiami.com/",
      services: ["Specialized in Abortions", "Free Pregnancy Tests"],
      other:
        "Website content is available in simplified Chines, French, Haitian Creole, Italian, Portuguese, Russian, and Spanish",
    },
    {
      resource: "Healthy Start Program ",
      address: {
        street: "18255 Homestead Ave.",
        apt: " ",
        city: "Miami",
        state: "FL",
        zipCode: "33157",
      },
      coordinate: {
        latitude: 25.5998657,
        longitude: -80.3555372,
      },
      phoneNumber: "305-324-2400",
      website:
        "miamidade.floridahealth.gov/programs-and-services/clinical-and-nutrition-services/healthy-start/index.html",
      services: [
        "Care Coordinator",
        "Nutritional Advice",
        "Counseling",
        "Parenting Support",
        "Childbirth Education",
        "Breastfeeding Education",
      ],
      other: "Contact E-mail: miamidade@flhealth.gov ",
    },
    {
      resource: "Banyan Health Systems",
      address: {
        street: "10720 Caribbean Blvd.",
        apt: "420",
        city: "Cutler Bay",
        state: "FL",
        zipCode: "33189",
      },
      coordinate: {
        latitude: 25.57627,
        longitude: -80.36571,
      },
      phoneNumber: "786-293-9544",
      website: "banyanhealth.org/service/primary-health/",
      services: [
        "Prenatal care",
        "Lab services",
        "Pharmacy",
        "Family Planning",
        "Immunization",
      ],
      other: "",
    },
    {
      resource: "Respect Life Miami",
      address: {
        street: "4747 Hollywood Blvd.",
        apt: "103",
        city: "Hollywood",
        state: "FL",
        zipCode: "33021",
      },
      coordinate: {
        latitude: 26.01128,
        longitude: -80.142967,
      },
      phoneNumber: "954-981-2922",
      website: "respectlifemiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Materials",
        "Medical Care",
        "Ultrasound",
      ],
      other:
        "Services are offered in Spanish, English and Creole as well as other languages",
    },
    {
      resource: "Respect Life Miami",
      address: {
        street: "5115 Coconut Creek Parkway",
        apt: "",
        city: "Margate",
        state: "FL",
        zipCode: "33063",
      },
      coordinate: {
        latitude: 26.24451,
        longitude: -80.19337,
      },
      phoneNumber: "954-977-7769",
      website: "respectlifemiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Infant Formula, Diapers, Free Materials",
        "Medical Care Parent and Baby",
        "Ultrasound",
      ],
      other:
        "Services are offered in Spanish, English and Creole as well as other languages",
    },
    {
      resource: "Respect Life Miami",
      address: {
        street: "525 NE 13th St.",
        apt: "",
        city: "Fort Lauderdale",
        state: "FL",
        zipCode: "33304",
      },
      coordinate: {
        latitude: 26.14261,
        longitude: -80.13853,
      },
      phoneNumber: "954-565-0229",
      website: "respectlifemiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Infant Formula, Diapers, Free Materials",
        "Medical Care for the Parent and Baby",
        "Ultrasound",
      ],
      other:
        "Services are offered in Spanish, English and Creole as well as other languages",
    },
    {
      resource: "Respect Life Miami",
      address: {
        street: "4747 Hollywood Blvd.",
        apt: "101",
        city: "Hollywood",
        state: "FL",
        zipCode: "33021",
      },
      coordinate: {
        latitude: 26.01104,
        longitude: -80.19122,
      },
      phoneNumber: "954-963-2229",
      website: "respectlifemiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Infant Formula, Diapers, Free Materials",
        "Medical Care for the Parent and Baby",
        "Ultrasound",
      ],
      other:
        "Services are offered in Spanish, English and Creole as well as other languages",
    },
    {
      resource: "Respect Life Miami",
      address: {
        street: "1515 NW 167th St.",
        apt: "190",
        city: "Miami Gardens",
        state: "FL",
        zipCode: "33169",
      },
      coordinate: {
        latitude: 25.928,
        longitude: -80.22672,
      },
      phoneNumber: "786-452-0266",
      website: "respectlifemiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Infant Formula, Diapers, Free Materials",
        "Medical Care for the Parent and Baby",
        "Ultrasound",
      ],
      other:
        "Services are offered in Spanish, English and Creole as well as other languages",
    },
    {
      resource: "Respect Life Miami",
      address: {
        street: "3410 SW 107 Ave.",
        apt: "",
        city: "Miami",
        state: "FL",
        zipCode: "33165",
      },
      coordinate: {
        latitude: 27.24257,
        longitude: -80.84821,
      },
      phoneNumber: "305-273-8507",
      website: "respectlifemiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Infant Formula, Diapers, Free Materials",
        "Medical Care for the Parent and Baby",
        "Ultrasound",
      ],
      other:
        "Services are offered in Spanish, English and Creole as well as other languages",
    },
    {
      resource: "Heartbeat of Miami",
      address: {
        street: "660 NE 125th St.",
        apt: "",
        city: "North Miami",
        state: "FL",
        zipCode: "33161",
      },
      coordinate: {
        latitude: 29.92025,
        longitude: -82.80016,
      },
      phoneNumber: "305-685-6010",
      website: "heartbeatofmiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Sonograms",
        "Free Peer Counseling",
        "Free Parenting Education",
        "Free Adoption Referrals",
      ],
      other: "",
    },
    {
      resource: "Heartbeat of Miami",
      address: {
        street: "10100 SW 107th Ct.",
        apt: "",
        city: "Miami",
        state: "FL",
        zipCode: "33176",
      },
      coordinate: {
        latitude: 25.6749,
        longitude: -80.36933,
      },
      phoneNumber: "305-274-5105",
      website: "heartbeatofmiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Sonograms",
        "Free Peer Counseling",
        "Free Parenting Education",
        "Free Adoption Referrals",
      ],
      other: "",
    },
    {
      resource: "Heartbeat of Miami",
      address: {
        street: "390 W 49th St.",
        apt: "103",
        city: "Hialeah",
        state: "FL",
        zipCode: "33012",
      },
      coordinate: {
        latitude: 25.86644,
        longitude: -80.29034,
      },
      phoneNumber: "305-821-9970",
      website: "heartbeatofmiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Sonograms",
        "Free Peer Counseling",
        "Free Parenting Education",
        "Free Adoption Referrals",
      ],
      other: "",
    },
    {
      resource: "Heartbeat of Miami",
      address: {
        street: "4391 W Flagler St.",
        apt: "",
        city: "Miami",
        state: "FL",
        zipCode: "33134",
      },
      coordinate: {
        latitude: 25.77186,
        longitude: -80.268,
      },
      phoneNumber: "305-603-8668",
      website: "heartbeatofmiami.org/",
      services: [
        "Free Pregnancy Tests",
        "Free Sonograms",
        "Free Peer Counseling",
        "Free Parenting Education",
        "Free Adoption Referrals",
      ],
      other: "",
    },
    {
      resource: "Pregnancy Help Medical Clinics",
      address: {
        street: "390 West 49th St.",
        apt: "",
        city: "Hialeah",
        state: "FL",
        zipCode: "33012",
      },
      coordinate: {
        latitude: 25.86644,
        longitude: -80.29034,
      },
      phoneNumber: "305-821-9970",
      website: "pregnancyhelpclinics.org/en",
      services: [
        "Free Pregnancy Tests",
        "Ultrasound",
        "Housing referrals",
        "STD/STI Information",
        "Community Resource Connections",
      ],
      other: "Website content in English and Spanish",
    },
    {
      resource: "Pregnancy Help Medical Clinics",
      address: {
        street: "660 NE 125th St.",
        apt: "",
        city: "North Miami",
        state: "FL",
        zipCode: "33161",
      },
      coordinate: {
        latitude: 25.89033,
        longitude: -80.18523,
      },
      phoneNumber: "305-685-6010",
      website: "pregnancyhelpclinics.org/en",
      services: [
        "Free Pregnancy Tests",
        "Ultrasound",
        "Housing referrals",
        "STD/STI Information",
        "Community Resource Connections",
      ],
      other: "Website content in English and Spanish",
    },
    {
      resource: "Pregnancy Help Medical Clinics",
      address: {
        street: "10100 SW 107th Ct. ",
        apt: "",
        city: "Kendall",
        state: "FL",
        zipCode: "33176",
      },
      coordinate: {
        latitude: 25.6749,
        longitude: -80.36933,
      },
      phoneNumber: "305-274-5105",
      website: "pregnancyhelpclinics.org/en",
      services: [
        "Free Pregnancy Tests",
        "Ultrasound",
        "Housing referrals",
        "STD/STI Information",
        "Community Resource Connections",
      ],
      other: "Website content in English and Spanish",
    },
    {
      resource: "Pregnancy Help Medical Clinics",
      address: {
        street: "4391 W Flagler St.",
        apt: "",
        city: "Flagler",
        state: "FL",
        zipCode: "33134",
      },
      coordinate: {
        latitude: 25.77186,
        longitude: -80.268,
      },
      phoneNumber: "305-603-8668",
      website: "pregnancyhelpclinics.org/en",
      services: [
        "Free Pregnancy Tests",
        "Ultrasound",
        "Housing referrals",
        "STD/STI Information",
        "Community Resource Connections",
      ],
      other: "Website content in English and Spanish",
    },
    {
      resource: "Eve’s Hope",
      address: {
        street: "9000 SW 152nd St.",
        apt: "105",
        city: "Miami",
        state: "FL",
        zipCode: "33157",
      },
      coordinate: {
        latitude: 25.62842,
        longitude: -80.33985,
      },
      phoneNumber: "(786) 732-7911",
      website: "eveshope.info/",
      services: [
        "Free Pregnancy Tests",
        "Ultrasound",
        "Pre-Natal and Parenting Classes",
        "Free Baby Items ",
        "Counseling",
      ],
      other:
        "Information found online specified they meet with “immigrants and teenage girls” to provide these services as well ",
    },
    {
      resource: "Hope Women's Centers",
      address: {
        street: "2261 S. University Dr.",
        apt: "",
        city: "Davie",
        state: "FL",
        zipCode: "33324",
      },
      coordinate: {
        latitude: 25.96666,
        longitude: -80.24679,
      },
      phoneNumber: "954-452-9459",
      website: "hopewomenscenters.com/",
      services: [
        "Housing Referrals",
        "Medical Referrals",
        "Parenting Education",
        "Parenting Education ",
        "STD/STI Tests, Treatment and Information",
      ],
      other: "Photo ID with birth-date required for medical services.",
    },
    {
      resource: "Hope Women's Centers",
      address: {
        street: "1400 E. Oakland Park Blvd.",
        apt: "201",
        city: "Ft. Lauderdale",
        state: "FL",
        zipCode: "33334",
      },
      coordinate: {
        latitude: 26.16645,
        longitude: -80.12848,
      },
      phoneNumber: "954-568-2616",
      website: "hopewomenscenters.com/",
      services: [
        "Housing Referrals",
        "Medical Referrals",
        "Parenting Education",
        "Parenting Education ",
        "STD/STI Tests, Treatment and Information",
      ],
      other: "Photo ID with birth-date required for medical services.",
    },
    {
      resource: "Hope Women's Centers",
      address: {
        street: "943 SW 71 Ave. (Rock Island Road)",
        apt: "",
        city: "North Lauderdale",
        state: "FL",
        zipCode: "33068",
      },
      coordinate: {
        latitude: 26.23024,
        longitude: -80.2216,
      },
      phoneNumber: "954-726-7464",
      website: "hopewomenscenters.com/",
      services: [
        "Housing Referrals",
        "Medical Referrals",
        "Parenting Education",
        "Parenting Education ",
        "STD/STI Tests, Treatment and Information",
      ],
      other: "Photo ID with birth-date required for medical services.",
    },
    {
      resource: "Love and Care Pregnancy Resources",
      address: {
        street: "133 Ponce de Leon Blvd.",
        apt: "",
        city: "Miami",
        state: "FL",
        zipCode: "33135",
      },
      coordinate: {
        latitude: 25.77031,
        longitude: -80.25478,
      },
      phoneNumber: "(305) 442-9448",
      website: "",
      services: [
        "Pregnancy Test",
        "Counseling During and After Pregnancy",
        "Assistance with Application for Medicaid",
        "Food Stamps",
        "Monopoly Money Given to Mothers",
      ],
      other:
        "Clients must fill out an intake form for an individual need assessment. Services in English and Spanish",
    },
    {
      resource:
        "South Miami Hospital -Center for Women and Infants -Great Expectations",
      address: {
        street: "6200 SW 73rd St.",
        apt: "",
        city: "Miami",
        state: "FL",
        zipCode: "33143",
      },
      coordinate: {
        latitude: 25.70336,
        longitude: -80.2907,
      },
      phoneNumber: "(786) 662-5026",
      website:
        "baptisthealth.net/en/facilities/south-miami-hospital/maternity/pages/great-expectations-at-south-miami-hospital.aspx",
      services: [
        "Practical Information About Pregnancy",
        "Counselor is Available by Phone",
      ],
      other:
        "English only and available to those delivering at South Miami Hospital",
    },
    {
      resource: "Family Planning",
      address: {
        street: "1350 NW 14th St.",
        apt: "325",
        city: "Miami",
        state: "FL",
        zipCode: "33125",
      },
      coordinate: {
        latitude: 25.78684,
        longitude: -80.21819,
      },
      phoneNumber: "(305) 575-3800",
      website:
        "miamidade.floridahealth.gov/programs-and-services/clinical-and-nutrition-services/womens-health/women_family%20planning/index.html",
      services: [
        "Yearly Exams for Women",
        "STD/STI Counseling and Treatment",
        "Emergency Testing",
        "HIV/AIDs Testing & Counseling",
        "Pregnancy Testing",
      ],
      other:
        "Services are free for adolescents, Sliding scale payments are available, On your first visit, you will be asked to bring information on your income and picture ID to determine the cost, service available in English, Spanish, and Creole ",
    },
    {
      resource: "Family Planning",
      address: {
        street: "11865 SW 26 St.",
        apt: "J2",
        city: "Miami",
        state: "FL",
        zipCode: "33175",
      },
      coordinate: {
        latitude: 25.76034,
        longitude: -80.19404,
      },
      phoneNumber: " (305) 225-5950",
      website:
        "miamidade.floridahealth.gov/programs-and-services/clinical-and-nutrition-services/womens-health/women_family%20planning/index.html",
      services: [
        "Yearly Exams for Women",
        "STD/STI Counseling and Treatment",
        "Emergency Testing",
        "HIV/AIDs Testing & Counseling",
        "Pregnancy Testing",
      ],
      other:
        "Services are free for adolescents, Sliding scale payments are available, On your first visit, you will be asked to bring information on your income and picture ID to determine the cost, service available in English, Spanish, and Creole ",
    },
    {
      resource: "Family Planning",
      address: {
        street: "300 NE 80th Terr.",
        apt: "",
        city: "Miami",
        state: "FL",
        zipCode: "33138",
      },
      coordinate: {
        latitude: 25.84877,
        longitude: -80.19072,
      },
      phoneNumber: "305-575-3800",
      website:
        "miamidade.floridahealth.gov/programs-and-services/clinical-and-nutrition-services/womens-health/women_family%20planning/index.html",
      services: [
        "Yearly Exams for Women",
        "STD/STI Counseling and Treatment",
        "Emergency Testing",
        "HIV/AIDs Testing & Counseling",
        "Pregnancy Testing",
      ],
      other:
        "Services are free for adolescents, Sliding scale payments are available, On your first visit, you will be asked to bring information on your income and picture ID to determine the cost, service available in English, Spanish, and Creole ",
    },
    {
      resource: "Nurse Family Partnership",
      address: {
        street: "7205 NW 19th St.",
        apt: "500",
        city: "Miami",
        state: "FL",
        zipCode: "33126",
      },
      coordinate: {
        latitude: 25.7926,
        longitude: -80.31392,
      },
      phoneNumber: "305-541-0210",
      website: "hscmd.org/programs-initiatives/nurse-family-partnership/#",
      services: [
        "Introduces Vulnerable First-Time Parents to Caring Maternal and Child Health Nurses",
      ],
      other:
        "Any woman who is pregnant with her first child, meets incomeeligibility requirements, and lives within the service area can enroll. -Women are encouraged to enroll as early as possible, but no later than 28th week gestation",
    },
    {
      resource: "Compassion Ministries by Florida Baptist Children’s Homes ",
      address: {
        street: "7748 SW 95th Terr.",
        apt: "",
        city: "Miami",
        state: "FL",
        zipCode: "33815",
      },
      coordinate: {
        latitude: 25.68144,
        longitude: -80.32002,
      },
      phoneNumber: "305-271-4121",
      website: "fbchomes.org/",
      services: ["Provides Foods and Items to Those in Crisis."],
      other: "Miami.FL@FBCHomes.org",
    },
    {
      resource: "Family Resource Center",
      address: {
        street: "155 South Miami Ave.",
        apt: "400",
        city: "Miami",
        state: "FL",
        zipCode: "33130",
      },
      coordinate: {
        latitude: 25.68144,
        longitude: -80.32002,
      },
      phoneNumber: "(305) 374-6006",
      website: "fbchomes.org/",
      services: ["Provides Items Upon Graduation."],
      other: "",
    },
    {
      resource: "The True Deliverance Church of Christ",
      address: {
        street: "18300 SW 109th Ave.",
        apt: "400",
        city: "Miami",
        state: "FL",
        zipCode: "33157",
      },
      coordinate: {
        latitude: 25.59864,
        longitude: -80.36961,
      },
      phoneNumber: "(305) 254-2163",
      website: "",
      services: ["Provides Free Clothes and Items for Moms and the Newborn"],
      other: "",
    },
    {
      resource: "HealthConnect In The Early Years",
      address: {
        street: "701 SW 27th Ave.",
        apt: "1401",
        city: "Miami",
        state: "FL",
        zipCode: "33157",
      },
      coordinate: {
        latitude: 25.76572,
        longitude: -80.23824,
      },
      phoneNumber: "(305) 646-6868",
      website: "",
      services: [
        "Health Education, Prevention and Support to Improve Maternal Healthy",
      ],
      other: "",
    },
    {
      resource: "Catholic Charities - Healthy Start",
      address: {
        street: "3675 South Miami Ave.",
        apt: "",
        city: "Miami",
        state: "FL",
        zipCode: "33133",
      },
      coordinate: {
        latitude: 25.76572,
        longitude: -80.23824,
      },
      phoneNumber: "(305) 854-9712",
      website: "",
      services: ["Parenting Skill Classes", "Counseling"],
      other: "",
    },
  ];
}
