export default function STDS() {
  return [
    {
      name: 'bacterialVaginosis',
      symptoms: 'bacterialVaginosisSymptoms',
      diagnosis: 'bacterialVaginosisDiagnosis',
      treatment: 'bacterialVaginosisTreatment',
      consequences: 'bacterialVaginosisConsequences',
      safeSex: 'bacterialVaginosisSafeSex',
    },
    {
      name: 'chlamydia',
      symptoms: 'chlamydiaSymptoms',
      diagnosis: 'chlamydiaDiagnosis',
      treatment: 'chlamydiaTreatment',
      consequences: 'chlamydiaConsequences',
      safeSex: 'chlamydiaSafeSex',
    },
    {
      name: 'genitalHerpes',
      symptoms: 'genitalHerpesSymptoms',
      diagnosis: 'genitalHerpesDiagnosis',
      treatment: 'genitalHerpesTreatment',
      consequences: 'genitalHerpesConsequences',
      safeSex: 'genitalHerpesSafeSex',
    },
    {
      name: 'gonorrhea',
      symptoms: 'gonorrheaSymptoms',
      diagnosis: 'gonorrheaDiagnosis',
      treatment: 'gonorrheaTreatment',
      consequences: 'gonorrheaConsequences',
      safeSex: 'gonorrheaSafeSex',
    },
    {
      name: 'hepatitisB',
      symptoms: 'hepatitisBSymptoms',
      diagnosis: 'hepatitisBDiagnosis',
      treatment: 'hepatitisBTreatment',
      consequences: 'hepatitisBConsequences',
      safeSex: 'hepatitisBSafeSex',
      website:
        'http://www.floridahealth.gov/diseases-and-conditions/perinatal-hepatitis-b/index.html',
    },
    {
      name: 'HIVAIDS',
      symptoms: 'HIVAIDSSymptoms',
      diagnosis: 'HIVAIDSDiagnosis',
      treatment: 'HIVAIDSTreatment',
      consequences: 'HIVAIDSConsequences',
      safeSex: 'HIVAIDSSafeSex',
    },
    {
      name: 'HPV',
      symptoms: 'HPVSymptoms',
      diagnosis: 'HPVDiagnosis',
      treatment: 'HPVTreatment',
      consequences: 'HPVConsequences',
      safeSex: 'HPVSafeSex',
    },
    {
      name: 'syphilis',
      symptoms: 'syphilisSymptoms',
      diagnosis: 'syphilisDiagnosis',
      treatment: 'syphilisTreatment',
      consequences: 'syphilisConsequences',
      safeSex: 'syphilisSafeSex',
    },
    {
      name: 'trichomoniasis',
      symptoms: 'trichomoniasisSymptoms',
      diagnosis: 'trichomoniasisDiagnosis',
      treatment: 'trichomoniasisTreatment',
      consequences: 'trichomoniasisConsequences',
      safeSex: 'trichomoniasisSafeSex',
    },
    {
      name: 'zika',
      symptoms: 'zikaSymptoms',
      diagnosis: 'zikaDiagnosis',
      treatment: 'zikaTreatment',
      consequences: 'zikaConsequences',
      safeSex: 'zikaSafeSex',
      website: 'http://www.cdc.gov/zika/index.html',
    },
  ];
}
