export default function STDS() {
  return [
    {
      name: "gonorrhea",
      symptoms: "gonorrheaSymptoms",
      diagnosis: "gonorrheaDiagnosis",
      treatment: "gonorrheaTreatment",
      consequences: "gonorrheaConsequences",
      safeSex: "gonorrheaSafeSex",
    },
    {
      name: "chlamydia",
      symptoms: "chlamydiaSymptoms",
      diagnosis: "chlamydiaDiagnosis",
      treatment: "chlamydiaTreatment",
      consequences: "chlamydiaConsequences",
      safeSex: "chlamydiaSafeSex",
    },
    {
      name: "HPV",
      symptoms: "HPVSymptoms",
      diagnosis: "HPVDiagnosis",
      treatment: "HPVTreatment",
      consequences: "HPVConsequences",
      safeSex: "HPVSafeSex",
    },
    {
      name: "genitalHerpes",
      symptoms: "genitalHerpesSymptoms",
      diagnosis: "genitalHerpesDiagnosis",
      treatment: "genitalHerpesTreatment",
      consequences: "genitalHerpesConsequences",
      safeSex: "genitalHerpesSafeSex",
    },
    {
      name: "syphilis",
      symptoms: "syphilisSymptoms",
      diagnosis: "syphilisDiagnosis",
      treatment: "syphilisTreatment",
      consequences: "syphilisConsequences",
      safeSex: "syphilisSafeSex",
    },
    {
      name: "bacterialVaginosis",
      symptoms: "bacterialVaginosisSymptoms",
      diagnosis: "bacterialVaginosisDiagnosis",
      treatment: "bacterialVaginosisTreatment",
      consequences: "bacterialVaginosisConsequences",
      safeSex: "bacterialVaginosisSafeSex",
    },
    {
      name: "trichomoniasis",
      symptoms: "trichomoniasisSymptoms",
      diagnosis: "trichomoniasisDiagnosis",
      treatment: "trichomoniasisTreatment",
      consequences: "trichomoniasisConsequences",
      safeSex: "trichomoniasisSafeSex",
    },
    {
      name: "HIVAIDS",
      symptoms: "HIVAIDSymptoms",
      diagnosis: "HIVAIDSDiagnosis",
      treatment: "HIVAIDSTreatment",
      consequences: "HIVAIDSConsequences",
      safeSex: "HIVAIDSSafeSex",
    },
  ];
}
